//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.WebFace.Store.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.WebFace.Store.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ALIAS {
            get {
                return ResourceManager.GetString("ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código aduanero.
        /// </summary>
        public static string CUSTOM_CODE {
            get {
                return ResourceManager.GetString("CUSTOM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsión.
        /// </summary>
        public static string DUE_DATE {
            get {
                return ResourceManager.GetString("DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string DUE_OF_PAYMENT {
            get {
                return ResourceManager.GetString("DUE_OF_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vto..
        /// </summary>
        public static string EXPIRATION_DATE {
            get {
                return ResourceManager.GetString("EXPIRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda por kilo.
        /// </summary>
        public static string HELP_KILO {
            get {
                return ResourceManager.GetString("HELP_KILO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura Recibda.
        /// </summary>
        public static string INVOICE {
            get {
                return ResourceManager.GetString("INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas de factura.
        /// </summary>
        public static string INVOICE_LINE_LIST {
            get {
                return ResourceManager.GetString("INVOICE_LINE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas.
        /// </summary>
        public static string INVOICE_LIST {
            get {
                return ResourceManager.GetString("INVOICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avisar beneficio mínimo.
        /// </summary>
        public static string MINIMUM_PROFIT_ALERT {
            get {
                return ResourceManager.GetString("MINIMUM_PROFIT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje beneficio mínimo.
        /// </summary>
        public static string MINIMUM_PROFIT_P {
            get {
                return ResourceManager.GetString("MINIMUM_PROFIT_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock mínimo.
        /// </summary>
        public static string MINIMUM_STOCK {
            get {
                return ResourceManager.GetString("MINIMUM_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string OBSERVATIONS {
            get {
                return ResourceManager.GetString("OBSERVATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulto.
        /// </summary>
        public static string PACKAGE {
            get {
                return ResourceManager.GetString("PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilos por bulto.
        /// </summary>
        public static string PACKAGE_KILOS {
            get {
                return ResourceManager.GetString("PACKAGE_KILOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string PAYMENT_AMOUNT {
            get {
                return ResourceManager.GetString("PAYMENT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio de Pago.
        /// </summary>
        public static string PAYMENT_WAY {
            get {
                return ResourceManager.GetString("PAYMENT_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string PAYMENTS {
            get {
                return ResourceManager.GetString("PAYMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos.
        /// </summary>
        public static string PRODUCT_DATA {
            get {
                return ResourceManager.GetString("PRODUCT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar producto.
        /// </summary>
        public static string PRODUCT_EDIT {
            get {
                return ResourceManager.GetString("PRODUCT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string PRODUCT_LIST {
            get {
                return ResourceManager.GetString("PRODUCT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos.
        /// </summary>
        public static string PRODUCTS {
            get {
                return ResourceManager.GetString("PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acreedor.
        /// </summary>
        public static string PROVIDER {
            get {
                return ResourceManager.GetString("PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Acreedor.
        /// </summary>
        public static string PROVIDER_TYPE {
            get {
                return ResourceManager.GetString("PROVIDER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string PROVIDERS {
            get {
                return ResourceManager.GetString("PROVIDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta contable de compra.
        /// </summary>
        public static string PURCHASE_ACCOUNTANT_ACCOUNT {
            get {
                return ResourceManager.GetString("PURCHASE_ACCOUNTANT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de compra.
        /// </summary>
        public static string PURCHASE_PRICE {
            get {
                return ResourceManager.GetString("PURCHASE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Registro.
        /// </summary>
        public static string REGISTRY_DATE {
            get {
                return ResourceManager.GetString("REGISTRY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta contable de venta.
        /// </summary>
        public static string SALE_ACCOUNTANT_ACCOUNT {
            get {
                return ResourceManager.GetString("SALE_ACCOUNTANT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Venta.
        /// </summary>
        public static string SALE_PRICE {
            get {
                return ResourceManager.GetString("SALE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string SERIE {
            get {
                return ResourceManager.GetString("SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avisar stock.
        /// </summary>
        public static string STOCK_ALERT {
            get {
                return ResourceManager.GetString("STOCK_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén.
        /// </summary>
        public static string STORE {
            get {
                return ResourceManager.GetString("STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string SUPPLIER {
            get {
                return ResourceManager.GetString("SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Imp..
        /// </summary>
        public static string TAX_BASE {
            get {
                return ResourceManager.GetString("TAX_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imp..
        /// </summary>
        public static string TAXES {
            get {
                return ResourceManager.GetString("TAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Imp..
        /// </summary>
        public static string TAXES_PERCENT {
            get {
                return ResourceManager.GetString("TAXES_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de venta.
        /// </summary>
        public static string TYPE_SALE {
            get {
                return ResourceManager.GetString("TYPE_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitario.
        /// </summary>
        public static string UNITARY {
            get {
                return ResourceManager.GetString("UNITARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF/CIF.
        /// </summary>
        public static string VAT_NUMBER {
            get {
                return ResourceManager.GetString("VAT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficio cero.
        /// </summary>
        public static string ZERO_PROFIT {
            get {
                return ResourceManager.GetString("ZERO_PROFIT", resourceCulture);
            }
        }
    }
}
