//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Store.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Store.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acreedores.
        /// </summary>
        public static string ACREEDORES {
            get {
                return ResourceManager.GetString("ACREEDORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes Recibidos: Facturados.
        /// </summary>
        public static string ALBARAN_FACTURADOS {
            get {
                return ResourceManager.GetString("ALBARAN_FACTURADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes Recibidos: No Facturados.
        /// </summary>
        public static string ALBARAN_NO_FACTURADOS {
            get {
                return ResourceManager.GetString("ALBARAN_NO_FACTURADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes Recibidos: Listado Completo.
        /// </summary>
        public static string ALBARAN_TODOS {
            get {
                return ResourceManager.GetString("ALBARAN_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedients de Alimentación.
        /// </summary>
        public static string ALIMENTACION {
            get {
                return ResourceManager.GetString("ALIMENTACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedients de Almacén.
        /// </summary>
        public static string ALMACEN {
            get {
                return ResourceManager.GetString("ALMACEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Almacén.
        /// </summary>
        public static string ALMACEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Almacén:.
        /// </summary>
        public static string ALMACEN_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Almacén:.
        /// </summary>
        public static string ALMACEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén.
        /// </summary>
        public static string ALMACEN_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Concepto.
        /// </summary>
        public static string CONCEPTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Concepto.
        /// </summary>
        public static string CONCEPTO_NEW_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto Libre:.
        /// </summary>
        public static string CONCEPTOLIBRE_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTOLIBRE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Contenedor.
        /// </summary>
        public static string CONTAINER_ADD_TITLE {
            get {
                return ResourceManager.GetString("CONTAINER_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenedor {0}.
        /// </summary>
        public static string CONTAINER_TITLE {
            get {
                return ResourceManager.GetString("CONTAINER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Albarán de Entrada.
        /// </summary>
        public static string CREAR_ALBARAN {
            get {
                return ResourceManager.GetString("CREAR_ALBARAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Factura.
        /// </summary>
        public static string CREAR_FACTURA {
            get {
                return ResourceManager.GetString("CREAR_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despachantes.
        /// </summary>
        public static string DESPACHANTE_TITLE {
            get {
                return ResourceManager.GetString("DESPACHANTE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha del Empleado.
        /// </summary>
        public static string EMPLEADO_TI {
            get {
                return ResourceManager.GetString("EMPLEADO_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        public static string EMPLOYEE {
            get {
                return ResourceManager.GetString("EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Empleado.
        /// </summary>
        public static string EMPLOYEE_ADD_TITLE {
            get {
                return ResourceManager.GetString("EMPLOYEE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de Empleado: {0}.
        /// </summary>
        public static string EMPLOYEE_TITLE {
            get {
                return ResourceManager.GetString("EMPLOYEE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partes de trabajo de empleados.
        /// </summary>
        public static string EMPLOYEE_WORKREPORTS_LIST {
            get {
                return ResourceManager.GetString("EMPLOYEE_WORKREPORTS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Expediente.
        /// </summary>
        public static string EXPEDIENT_ADD_TITLE {
            get {
                return ResourceManager.GetString("EXPEDIENT_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediente {0}.
        /// </summary>
        public static string EXPEDIENT_TITLE {
            get {
                return ResourceManager.GetString("EXPEDIENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Expediente:.
        /// </summary>
        public static string EXPEDIENTE_INPUT_TITLE {
            get {
                return ResourceManager.GetString("EXPEDIENTE_INPUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externo a la Explotación.
        /// </summary>
        public static string EXTERNAL_HEAD {
            get {
                return ResourceManager.GetString("EXTERNAL_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas: Pagadas.
        /// </summary>
        public static string FACTURA_RECIBIDAS_PAGADAS {
            get {
                return ResourceManager.GetString("FACTURA_RECIBIDAS_PAGADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas: Pendientes.
        /// </summary>
        public static string FACTURA_RECIBIDAS_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURA_RECIBIDAS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Recibidas: Listado Completo.
        /// </summary>
        public static string FACTURA_RECIBIDAS_TODAS {
            get {
                return ResourceManager.GetString("FACTURA_RECIBIDAS_TODAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Factura.
        /// </summary>
        public static string FACTURAR {
            get {
                return ResourceManager.GetString("FACTURAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familias:.
        /// </summary>
        public static string FAMILIA {
            get {
                return ResourceManager.GetString("FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedients de Ganado.
        /// </summary>
        public static string GANADO {
            get {
                return ResourceManager.GetString("GANADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos: {0}.
        /// </summary>
        public static string GASTOS_TITLE {
            get {
                return ResourceManager.GetString("GASTOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Pagos.
        /// </summary>
        public static string GENERAR_PAGOS {
            get {
                return ResourceManager.GetString("GENERAR_PAGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe asignado a la Factura.
        /// </summary>
        public static string IMPORTE_PAGO_FACTURA {
            get {
                return ResourceManager.GetString("IMPORTE_PAGO_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe asignado al Gasto.
        /// </summary>
        public static string IMPORTE_PAGO_GASTO {
            get {
                return ResourceManager.GetString("IMPORTE_PAGO_GASTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe asignado a la Nómina.
        /// </summary>
        public static string IMPORTE_PAGO_NOMINA {
            get {
                return ResourceManager.GetString("IMPORTE_PAGO_NOMINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Inventario.
        /// </summary>
        public static string INVENTARIOALMACEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("INVENTARIOALMACEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Inventario:.
        /// </summary>
        public static string INVENTARIOALMACEN_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("INVENTARIOALMACEN_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Inventario:.
        /// </summary>
        public static string INVENTARIOALMACEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("INVENTARIOALMACEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kits de productos.
        /// </summary>
        public static string KITS {
            get {
                return ResourceManager.GetString("KITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Productos.
        /// </summary>
        public static string LISTA_PRODUCTOS_TITLE {
            get {
                return ResourceManager.GetString("LISTA_PRODUCTOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos asociados a un proveedor.
        /// </summary>
        public static string LISTAPRODPROV_TITLE {
            get {
                return ResourceManager.GetString("LISTAPRODPROV_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedients de Maquinaria.
        /// </summary>
        public static string MAQUINARIA {
            get {
                return ResourceManager.GetString("MAQUINARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navieras.
        /// </summary>
        public static string NAVIERAS {
            get {
                return ResourceManager.GetString("NAVIERAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obras.
        /// </summary>
        public static string OBRA {
            get {
                return ResourceManager.GetString("OBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Pago.
        /// </summary>
        public static string PAGO_ADD_TITLE {
            get {
                return ResourceManager.GetString("PAGO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle del Pago.
        /// </summary>
        public static string PAGO_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("PAGO_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pago:.
        /// </summary>
        public static string PAGO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PAGO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string PAGO_GASTO_TI {
            get {
                return ResourceManager.GetString("PAGO_GASTO_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string PAGOS {
            get {
                return ResourceManager.GetString("PAGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Ficha de Pagos.
        /// </summary>
        public static string PAGOS_TI {
            get {
                return ResourceManager.GetString("PAGOS_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos: {0}.
        /// </summary>
        public static string PAGOS_TITLE {
            get {
                return ResourceManager.GetString("PAGOS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Pedido.
        /// </summary>
        public static string PEDIDOPROVEEDOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("PEDIDOPROVEEDOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del pedido:.
        /// </summary>
        public static string PEDIDOPROVEEDOR_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("PEDIDOPROVEEDOR_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pedido:.
        /// </summary>
        public static string PEDIDOPROVEEDOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PEDIDOPROVEEDOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Precio.
        /// </summary>
        public static string PRECIO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PRECIO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Precio.
        /// </summary>
        public static string PRECIO_NEW_TITLE {
            get {
                return ResourceManager.GetString("PRECIO_NEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio Exterior.
        /// </summary>
        public static string PRESTAMOS_COMERCIO_EXTERIOR {
            get {
                return ResourceManager.GetString("PRESTAMOS_COMERCIO_EXTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string PRODUCTO {
            get {
                return ResourceManager.GetString("PRODUCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar un producto a un proveedor.
        /// </summary>
        public static string PRODUCTOPROV_TITLE {
            get {
                return ResourceManager.GetString("PRODUCTOPROV_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Proyecto.
        /// </summary>
        public static string PROJECT_ADD_TITLE {
            get {
                return ResourceManager.GetString("PROJECT_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto {0}.
        /// </summary>
        public static string PROJECT_TITLE {
            get {
                return ResourceManager.GetString("PROJECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Proveedor:.
        /// </summary>
        public static string PROVEEDOR_INPUT_TITLE {
            get {
                return ResourceManager.GetString("PROVEEDOR_INPUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha del Proveedor.
        /// </summary>
        public static string PROVEEDOR_TI {
            get {
                return ResourceManager.GetString("PROVEEDOR_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string PROVEEDORES {
            get {
                return ResourceManager.GetString("PROVEEDORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puertos.
        /// </summary>
        public static string PUERTO_TITLE {
            get {
                return ResourceManager.GetString("PUERTO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razas.
        /// </summary>
        public static string RAZAANIMAL_TITLE {
            get {
                return ResourceManager.GetString("RAZAANIMAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un puerto.
        /// </summary>
        public static string SELECT_PUERTO_TITLE {
            get {
                return ResourceManager.GetString("SELECT_PUERTO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una categoría.
        /// </summary>
        public static string SELECT_WORK_REPORT_CATEGORY {
            get {
                return ResourceManager.GetString("SELECT_WORK_REPORT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series:.
        /// </summary>
        public static string SERIE {
            get {
                return ResourceManager.GetString("SERIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string SERIE_TITLE {
            get {
                return ResourceManager.GetString("SERIE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva entrada de Stock.
        /// </summary>
        public static string STOCK_ADD_TITLE {
            get {
                return ResourceManager.GetString("STOCK_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar entrada de Stock.
        /// </summary>
        public static string STOCK_EDIT_TITLE {
            get {
                return ResourceManager.GetString("STOCK_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Animales.
        /// </summary>
        public static string TIPOANIMAL_TITLE {
            get {
                return ResourceManager.GetString("TIPOANIMAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Ganado.
        /// </summary>
        public static string TIPOGANADO_TITLE {
            get {
                return ResourceManager.GetString("TIPOGANADO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Ventas de Expedient.
        /// </summary>
        public static string VENTAS_EXPEDIENTE_REPORT_TITLE {
            get {
                return ResourceManager.GetString("VENTAS_EXPEDIENTE_REPORT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Obra.
        /// </summary>
        public static string WORK_ADD_TITLE {
            get {
                return ResourceManager.GetString("WORK_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra {0}.
        /// </summary>
        public static string WORK_TITLE {
            get {
                return ResourceManager.GetString("WORK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
