//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Store.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Store.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una factura de este tipo de acreedor asociada al expediente. ¿Desea establecer esta como la factura principal de este acreedor para el expediente seleccionado?.
        /// </summary>
        public static string ACREEDOR_EXISTENTE {
            get {
                return ResourceManager.GetString("ACREEDOR_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este producto tiene albaranes de compra o venta asociados..
        /// </summary>
        public static string ALBARAN_ASOCIADO {
            get {
                return ResourceManager.GetString("ALBARAN_ASOCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen albaranes asociados a esta serie, para eliminar esta serie deberá eliminar primero todos los albaranes vinculados..
        /// </summary>
        public static string ALBARANES_ASOCIADOS {
            get {
                return ResourceManager.GetString("ALBARANES_ASOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible asignar albaranes con IRPF distinto a una misma Factura..
        /// </summary>
        public static string ALBARANES_CON_IRPF_DISTINTO {
            get {
                return ResourceManager.GetString("ALBARANES_CON_IRPF_DISTINTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de bultos es inferior a la estimada ({0}). ¿Desea continuar?..
        /// </summary>
        public static string BULTOS_INFERIORES {
            get {
                return ResourceManager.GetString("BULTOS_INFERIORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bultos insuficientes. Cantidad actual:.
        /// </summary>
        public static string BULTOS_INSUFICIENTES {
            get {
                return ResourceManager.GetString("BULTOS_INSUFICIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de bultos es superior a la estimada ({0}). ¿Desea continuar?..
        /// </summary>
        public static string BULTOS_SUPERIORES {
            get {
                return ResourceManager.GetString("BULTOS_SUPERIORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GASTO KG: Es el total de los gastos asociados dividido entre los kg del expediente | COSTE KG: Es el PRECIO DE COMPRA + GASTO KG.
        /// </summary>
        public static string CAMPOS_EXPEDIENTES {
            get {
                return ResourceManager.GetString("CAMPOS_EXPEDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un problema con los gastos asociados a este expediente. Es probable que se haya asignado un concepto de factura a varios expedientes, lo que provoca este error..
        /// </summary>
        public static string DUPLICATED_EXPENSE_LINE {
            get {
                return ResourceManager.GetString("DUPLICATED_EXPENSE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un extracto de tarjeta asociado a este pago, con lo cual  no es posible modificarlo..
        /// </summary>
        public static string EXTRACTO_TARJETA_VENCIDO {
            get {
                return ResourceManager.GetString("EXTRACTO_TARJETA_VENCIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cambiar el Proveedor a una factura con albaranes asociados..
        /// </summary>
        public static string FACTURA_CON_ALBARANES {
            get {
                return ResourceManager.GetString("FACTURA_CON_ALBARANES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El IRPF del albarán que está intentando incluir no coincide con el existente y no es posible realizar la acción..
        /// </summary>
        public static string FACTURA_CON_IRPF_DISTINTO {
            get {
                return ResourceManager.GetString("FACTURA_CON_IRPF_DISTINTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe de la factura del proveedor ({0}) no coincide con el importe calculado a partir de los productos del expediente ({1}).&quot;.
        /// </summary>
        public static string FACTURA_PROVEEDOR_DIFERENTE {
            get {
                return ResourceManager.GetString("FACTURA_PROVEEDOR_DIFERENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para garantizar la trazabilidad de la mercancía es imprescindible indicar la factura del proveedor antes de introducir productos en el expediente..
        /// </summary>
        public static string FACTURA_PROVEEDOR_REQUIRED {
            get {
                return ResourceManager.GetString("FACTURA_PROVEEDOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para garantizar la trazabilidad de la mercancía es imprescindible indicar la fecha de factura del proveedor antes de introducir productos en el expediente..
        /// </summary>
        public static string FECHA_PROVEEDOR_REQUIRED {
            get {
                return ResourceManager.GetString("FECHA_PROVEEDOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cambiar el estado de un gasto asociado a un expediente.
        /// </summary>
        public static string GASTO_CON_EXPEDIENTE {
            get {
                return ResourceManager.GetString("GASTO_CON_EXPEDIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible cambiar el estado de un gasto con un pago asociado.
        /// </summary>
        public static string GASTO_CON_PAGO {
            get {
                return ResourceManager.GetString("GASTO_CON_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando facturas....
        /// </summary>
        public static string GENERANDO_FACTURAS {
            get {
                return ResourceManager.GetString("GENERANDO_FACTURAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importando albaranes seleccionados....
        /// </summary>
        public static string IMPORTANDO_ALBARANES {
            get {
                return ResourceManager.GetString("IMPORTANDO_ALBARANES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe total para este tipo de pago debe ser 0..
        /// </summary>
        public static string IMPORTE_PAGO_COMPENSACION {
            get {
                return ResourceManager.GetString("IMPORTE_PAGO_COMPENSACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar el proveedor de un expediente con productos asociados. Esta acción dejaría el expediente actual sin factura asociada..
        /// </summary>
        public static string IMPOSIBLE_CAMBIAR_PROVEEDOR_EXPEDIENTE {
            get {
                return ResourceManager.GetString("IMPOSIBLE_CAMBIAR_PROVEEDOR_EXPEDIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio introducido no es correcto..
        /// </summary>
        public static string INCORRECT_PRICE {
            get {
                return ResourceManager.GetString("INCORRECT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio introducido no es correcto. Debe ser mayor que 0..
        /// </summary>
        public static string INVALID_PRICE {
            get {
                return ResourceManager.GetString("INVALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen inventarios vinculados a este almacén, para eliminar este almacen deberá eliminar primero todos los inventarios vinculados..
        /// </summary>
        public static string INVENTARIO_ASOCIADO {
            get {
                return ResourceManager.GetString("INVENTARIO_ASOCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen elementos vinculados a este almacén, para eliminar este almacen deberá eliminar primero todos los elementos vinculados..
        /// </summary>
        public static string LINEA_ALMACEN_ASOCIADA {
            get {
                return ResourceManager.GetString("LINEA_ALMACEN_ASOCIADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para expedientes del tipo Maquinaria o Ganado la cantidad máxima por concepto debe ser 1. .
        /// </summary>
        public static string MAX_CANTIDAD_EXPEDIENTE_UNO {
            get {
                return ResourceManager.GetString("MAX_CANTIDAD_EXPEDIENTE_UNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han asociado familias a esta serie. Debe asociar al menos una familia para poder guardar la serie..
        /// </summary>
        public static string NO_FAMILIAS_ASOCIADAS {
            get {
                return ResourceManager.GetString("NO_FAMILIAS_ASOCIADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han asociado gastos del tipo {0} a este expediente. Para seleccionar la factura correspondiente utilice la pestaña de Gastos..
        /// </summary>
        public static string NO_GASTOS_ASOCIADOS {
            get {
                return ResourceManager.GetString("NO_GASTOS_ASOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe elegir un emisor antes de asignar la factura a un expediente..
        /// </summary>
        public static string NO_HOLDER {
            get {
                return ResourceManager.GetString("NO_HOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha puesto ningun precio. Asocie un precio al producto antes de continuar..
        /// </summary>
        public static string NO_PRICE {
            get {
                return ResourceManager.GetString("NO_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen productos asociados al expediente..
        /// </summary>
        public static string NO_PRODUCTS_ASSOC {
            get {
                return ResourceManager.GetString("NO_PRODUCTS_ASSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado ningún Proveedor..
        /// </summary>
        public static string NO_PROV_SELECTED {
            get {
                return ResourceManager.GetString("NO_PROV_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una serie.
        /// </summary>
        public static string NO_SERIE_SELECTED {
            get {
                return ResourceManager.GetString("NO_SERIE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado ningun Transportista..
        /// </summary>
        public static string NO_TRANS_SELECTED {
            get {
                return ResourceManager.GetString("NO_TRANS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario indicar unidades y bultos.
        /// </summary>
        public static string NO_UNIDADES_OR_BULTOS {
            get {
                return ResourceManager.GetString("NO_UNIDADES_OR_BULTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible asignar productos no unitarios a este tipo de expediente.
        /// </summary>
        public static string NO_UNITS_ALLOWED {
            get {
                return ResourceManager.GetString("NO_UNITS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAS. RECIBIDAS PTES. CON PREV. ANTERIOR AL {0}.
        /// </summary>
        public static string NOFITY_FACTURAS_RECIBIDAS_PENDIENTES {
            get {
                return ResourceManager.GetString("NOFITY_FACTURAS_RECIBIDAS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GASTOS PTES. CON VTO. ANTERIOR AL {0}.
        /// </summary>
        public static string NOFITY_GASTOS_PENDIENTES {
            get {
                return ResourceManager.GetString("NOFITY_GASTOS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGOS PTES. CON VTO. ANTERIOR AL {0}.
        /// </summary>
        public static string NOFITY_PAGOS_PENDIENTES {
            get {
                return ResourceManager.GetString("NOFITY_PAGOS_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar una nómina con un pago asociado..
        /// </summary>
        public static string NOMINA_CON_PAGO {
            get {
                return ResourceManager.GetString("NOMINA_CON_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMERCIO EXTERIOR CON VTO. ANTERIOR AL {0}.
        /// </summary>
        public static string NOTIFY_COMERCIO_EXTERIOR {
            get {
                return ResourceManager.GetString("NOTIFY_COMERCIO_EXTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGOS CON TARJETA VENCIDOS A {0}.
        /// </summary>
        public static string NOTIFY_PAGOS_TARJETAS_VENCIDOS {
            get {
                return ResourceManager.GetString("NOTIFY_PAGOS_TARJETAS_VENCIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGOS VENCIDOS A {0}.
        /// </summary>
        public static string NOTIFY_PAGOS_VENCIDOS {
            get {
                return ResourceManager.GetString("NOTIFY_PAGOS_VENCIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTOS CON STOCK NEGATIVO.
        /// </summary>
        public static string NOTIFY_STOCK_NEGATIVO {
            get {
                return ResourceManager.GetString("NOTIFY_STOCK_NEGATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La asignación {0:C2} es superior a la cantidad pendiente en el cobro {1:C2}.&quot;.
        /// </summary>
        public static string PAYMENT_BIGGER_ALLOCATION {
            get {
                return ResourceManager.GetString("PAYMENT_BIGGER_ALLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La asignación {0:C2} es inferior a la cantidad pendiente en el cobro {1:C2}.
        /// </summary>
        public static string PAYMENT_LESS_ALLOCATION {
            get {
                return ResourceManager.GetString("PAYMENT_LESS_ALLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El préstamo que está intentando borrar está asociado a un pago de factura y no es posible realizar la operación..
        /// </summary>
        public static string PRESTAMO_ASOCIADO_PAGO_FACTURA {
            get {
                return ResourceManager.GetString("PRESTAMO_ASOCIADO_PAGO_FACTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible borrar el préstamo seleccionado mientras tenga pagos asociados..
        /// </summary>
        public static string PRESTAMO_CON_PAGOS_ASOCIADOS {
            get {
                return ResourceManager.GetString("PRESTAMO_CON_PAGOS_ASOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El préstamo actual ya contiene pagos. ¿Desea mantener estos pagos junto con los nuevos que se generarán? En caso contrario, se anularán los pagos que existen actualmente..
        /// </summary>
        public static string PRESTAMO_CON_PAGOS_PREVIOS {
            get {
                return ResourceManager.GetString("PRESTAMO_CON_PAGOS_PREVIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La relación de kilos y unidades de este producto es {0} a 1 y el número de kilos y unidades de esta partida es el mismo. ¿Desea continuar?.
        /// </summary>
        public static string SAME_PIECES_AND_KILOS {
            get {
                return ResourceManager.GetString("SAME_PIECES_AND_KILOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirma la generación del extracto para la fecha {0}?.
        /// </summary>
        public static string SAVE_STATEMENT_CONFIRMATION {
            get {
                return ResourceManager.GetString("SAVE_STATEMENT_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un cliente.
        /// </summary>
        public static string SELECT_CLIENT {
            get {
                return ResourceManager.GetString("SELECT_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado ningún Despachante.
        /// </summary>
        public static string SELECT_CUSTOM_AGENCY {
            get {
                return ResourceManager.GetString("SELECT_CUSTOM_AGENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un emisor.
        /// </summary>
        public static string SELECT_HOLDER {
            get {
                return ResourceManager.GetString("SELECT_HOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado el Medio de pago.
        /// </summary>
        public static string SELECT_PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("SELECT_PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un puerto.
        /// </summary>
        public static string SELECT_PORT {
            get {
                return ResourceManager.GetString("SELECT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un producto.
        /// </summary>
        public static string SELECT_PRODUCT {
            get {
                return ResourceManager.GetString("SELECT_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado ninguna Naviera.
        /// </summary>
        public static string SELECT_SHIPPING_COMPANY {
            get {
                return ResourceManager.GetString("SELECT_SHIPPING_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este producto tiene movimientos de stock asociados..
        /// </summary>
        public static string STOCK_ASOCIADO {
            get {
                return ResourceManager.GetString("STOCK_ASOCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar ni eliminar el movimiento inicial ni un movimiento de stock asociado a un albarán..
        /// </summary>
        public static string STOCK_FACTURADO {
            get {
                return ResourceManager.GetString("STOCK_FACTURADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock insuficiente. Cantidad actual:.
        /// </summary>
        public static string STOCK_INSUFICIENTE {
            get {
                return ResourceManager.GetString("STOCK_INSUFICIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los tipos de interés introducidos no son válidos. Tenga en cuenta que la fecha de inicio de cada periodo debe ser previa a la de finalización y que los periodos no se pueden solapar entre ellos..
        /// </summary>
        public static string TIPOS_INTERES_NO_VALIDOS {
            get {
                return ResourceManager.GetString("TIPOS_INTERES_NO_VALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible asignar albaranes de titulares distintos a una misma factura..
        /// </summary>
        public static string TITULAR_FACTURA_DIFERENTE {
            get {
                return ResourceManager.GetString("TITULAR_FACTURA_DIFERENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando stock....
        /// </summary>
        public static string UPDATING_STOCK {
            get {
                return ResourceManager.GetString("UPDATING_STOCK", resourceCulture);
            }
        }
    }
}
